server:
  port: 8083

spring:
  application:
    name: Payment Service
  datasource:
    username: root
    password: admin123
    url: jdbc:postgresql://localhost:5433/payment
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace
kafka:
  host: localhost:9092
  group-id-config: payment

cache:
  redis:
    port: 8888
    host: localhost