version: "3.8"

services:
  prometheus:
    image: bitnami/prometheus:2.48.1
    container_name: prometheus
    restart: unless-stopped
    networks:
      - obs
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:10.2.2-ubuntu
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "9001:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - obs
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_DOMAIN=localhost
    depends_on:
      - prometheus

networks:
  obs:
    driver: bridge
    name: obs
