version: "3.8"

services:
  db-migrations:
    image: postgres:14-alpine
    container_name: db-migrations
    restart: unless-stopped
    privileged: true
    networks:
      - postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
    volumes:
      - ../postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

######################################## REDIS ########################################

  redis:
    image: "redis:7.2.3-alpine"
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "8888:6379"

######################################## KAFKA ########################################
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    ports:
      - "2181:2181"
  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka:2.13-2.8.1
    restart: unless-stopped
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
