spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: eureka-server


server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/zipkin