server:
  port: 8085

spring:
  application:
    name: Shop Service
  datasource:
    username: root
    password: admin123
    url: jdbc:postgresql://localhost:5433/shop
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
