server:
  port: 8081

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
#        - id: payment
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/v1/**
        - id: crm
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/**
        - id: notification
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/mail/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

security:
  configs:
    secretKey: "868DE142D37FB146EC9B45C7172FF61B60349E31C5DFB17ECC7D40865FF261D4"
    accessTokenExpiration: 1200000
    refreshTokenExpiration: 3600000
  whitelists:
    - "/api/v1/auth/"
    - "/api/v1/permissions/"
    - "/api/v1/roles/"
    - "/api/v1/mail/"
