server:
  port: 8088

########################################## Spring ##########################################
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: karson.ecommerce@gmail.com
    password: ozbtnfxwkvyfhvlj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: Notification-Service
  datasource:
    url: jdbc:postgresql://localhost:5433/notification
    username: root
    password: admin123
#  flyway:
#    baselineOnMigrate: true
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

########################################## Logs ##########################################
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

########################################## Caching - Redis ##########################################
cache:
  redis:
    host: localhost
    port: 8888

########################################## Trace and Monitor - Prometheus Zipkin ##########################################
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

########################################## Cloud manage services - Eureka ##########################################
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

########################################## Event Message - Kafka ##########################################
kafka:
#  enabled: true
  host: localhost:9092
  group-id-config: notification

########################################## Task Pool ##########################################
task:
  pools:
    enabled: true
    tasks-list:
      - name: emailTaskExecutor
        enabled: true
