server:
  port: 8088

spring:
  devtools:
    restart:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: khanhk56a12@gmail.com
    password: exscqriltlunpmdx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: Notification-Service

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true